### ISSUE TITLE
Backend.Core-Service

### ISSUE THREAD

**Issue by mkonicki** [oskardudycz/GoldenEye#21]
Please add interfaces to base service class.

**Comment by oskardudycz** [comment]
Good point. Will do.

**Comment by marekpiotrowski** [comment]
Guys, lack of an interface is not a bug. I'd call it 'clean code nazi' =D

**Comment by oskardudycz** [comment]
I would say that it's a bug in terms that I should create it from the beginning, but I forgot. Without interface it's harder to replace implementation if needed. I know that using framework that doesn't expose interfaces can be pain in the ass (vide .NET Membership).
@marekpiotrowski thank you for a comment :)

**Comment by oskardudycz** [comment]
Ready on branch VS2017
