### ISSUE TITLE
DDD.Sample doens't have autoregistered handlers

### ISSUE THREAD

**Issue by mjendza** [oskardudycz/GoldenEye#70]
I noticed that the DDD.Sample project doesn't have the example of automatic registering handlers implemented with  8.0.0 Backend.Core.DDD
It can be fixed with https://github.com/oskardudycz/GoldenEye/blob/master/src/Core/Backend.Core.DDD/Registration/Registration.cs#L108

**Comment by mjendza** [comment]
I found this issue on Scrutor https://github.com/khellang/Scrutor/issues/55

**Comment by mjendza** [comment]
error from the app 
`{
  "StatusCode": 500,
  "Error": "Error constructing handler for request of type MediatR.IRequestHandler`2[Backend.DDD.Sample.Contracts.Issues.Queries.GetIssues,System.Collections.Generic.IReadOnlyList`1[Backend.DDD.Sample.Contracts.Issues.Views.IssueView]]. Register your handlers with the container. See the samples in GitHub for examples."
}`

**Comment by oskardudycz** [comment]
Closed by #71
