### ISSUE TITLE
Netcore3.1 capability

### ISSUE THREAD

**Issue by Kirya522** [oskardudycz/GoldenEye#75]
GoldenEye.Backend.Core.WebApi.Modules contains reference to obsolete IHostingEnvironment.

**Comment by oskardudycz** [comment]
@Kirya522 yup. I need to work on the upgrade. That's the highest priority for me right now. Maybe I will be able to deliver that this week.

**Comment by Kirya522** [comment]
I was trying to do it myself, but there are a lot "local" problems in project maybe some dev dock will be useful. Is all the tests are actual?

**Comment by oskardudycz** [comment]
Yup, I started this upgrade, but I also faced some issues. I'll do it, probably this week.

**Comment by oskardudycz** [comment]
@Kirya522 there is progress. I managed to get the prerelease version with .NET Core 3.1 https://github.com/oskardudycz/GoldenEye/pull/74. 
It should be working, but I want to do a bit more refactoring (already did quite a lot - eg. removing the Identity/Security modules that I don't want to maintain anymore).
I'm also thinking about shortening the names of the packages.

But it should work. You can play around with the prerelease versions. I also added more helpers that are simplifying, even more, the boilerplate registration.

**Comment by Kirya522** [comment]
Cool, are you updated versions to pre-release manually inserting suffix or there is another way? I am just interested in.

**Comment by oskardudycz** [comment]
Yes, manually. Then build, packed and published automatically via AppVeyor.

**Comment by oskardudycz** [comment]
@Kirya522 I forgot to close the Issue - .NET Core 3.1 support is done also in the release version. Now I should probably target .NET 5 ;)
